# Generated by Django 5.1.1 on 2024-10-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='host UUID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='host name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
            ],
            options={
                'verbose_name': 'host',
                'verbose_name_plural': 'hosts',
            },
        ),
    ]
