# Generated by Django 5.1.1 on 2024-10-09 14:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_host', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='host UUID'),
        ),
    ]
