# Generated by Django 5.1.1 on 2024-10-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_host', '0002_alter_host_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='status',
            field=models.BooleanField(default=False, verbose_name='host status'),
        ),
    ]
