# Generated by Django 5.1.1 on 2024-10-10 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_host', '0003_host_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='status',
        ),
    ]
