# Generated by Django 5.1.1 on 2024-10-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_host', '0004_remove_host_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='status_analyze',
            field=models.BooleanField(default=False, verbose_name='analyze status'),
        ),
        migrations.AddField(
            model_name='host',
            name='status_cam',
            field=models.BooleanField(default=False, verbose_name='cam status'),
        ),
        migrations.AddField(
            model_name='host',
            name='status_command',
            field=models.BooleanField(default=False, verbose_name='command status'),
        ),
    ]
