# Generated by Django 5.1.1 on 2024-09-25 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_uuid', models.UUIDField(db_index=True, unique=True, verbose_name='face UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user face',
                'verbose_name_plural': 'user faces',
            },
        ),
    ]
