# Generated by Django 5.1.1 on 2024-09-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_face', '0002_userface_face_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userface',
            name='face_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True, verbose_name='face UUID'),
        ),
    ]
