# Generated by Django 5.1.1 on 2024-10-13 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_mall', '0002_facedetectionrecord_bot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facedetectionrecord',
            options={'get_latest_by': 'created_at', 'verbose_name': 'Face Detection Record', 'verbose_name_plural': 'Face Detection Records'},
        ),
    ]
